### ISSUE TITLE
[Case Studies] Update design and content for case study pages

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#1137]
The case study pages should be updated with new content and with new shapes/layout to match the rest of the website.

## Tasks
- Update Expedition case study – #1136
- Update EmbEDD case study – #1144
- Update Trainline case study – #1125
- Update Timify case study – #1145
- Create Qonto case study

## Resources
- [Copy](https://3.basecamp.com/3091689/buckets/11108058/todos/2661193683#__recording_2707425475)
- [Abstract](https://app.abstract.com/projects/f6401950-547a-11e9-a66d-7f6f3414ea33/branches/b0ed52ef-decf-4c50-a49a-b20c7c684109/collections/34327f4a-d1b0-4b6c-8bf4-10541cdb44d8)

**Comment by marhigh** [comment]
@locks the case study for Qonto is ready for review. You can take a look & give feedback to the relevant artboards here: 

- Mobile: https://share.goabstract.com/38538c76-4556-4f2f-872c-11909e1d12ae
- Tablet: https://share.goabstract.com/68c01398-58a2-45ac-ae2d-c5db70e59d93
- Desktop: https://share.goabstract.com/fbe158ae-3a4f-46d9-bc01-7945b43318fa

We should also update all the "Read More" components so that they link to the next case study, according to their order in the footer navigation. The updated design + text is also in Abstract. Should I create a separate issue for that?

**Comment by locks** [comment]
@marhigh a separate issue for the "Read More" links would be very helpful as that work can be done independently!
