### ISSUE TITLE
Initial state of text overlay isn't always correct

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1842]
On some pages, the initial state of the text overlay isn't positioned correctly, e.g. on these pages I'm scrolled all the way to the top of the page and the overlay should cover the entire words but doesn't:

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 16 32" src="https://user-images.githubusercontent.com/1510/185213457-b2a941aa-5090-4ffc-b0f9-7bdb44811748.png">
<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 16 56" src="https://user-images.githubusercontent.com/1510/185213486-ed5a662f-ece6-4ca2-81e1-689f3055d927.png">
<img width="451" alt="Bildschirmfoto 2022-08-17 um 20 50 50" src="https://user-images.githubusercontent.com/1510/185219459-e25d13f2-93ec-4892-9552-7cf928420456.png">

**Comment by marianneciara** [comment]
This fix is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/). 

I've added an alternative animation for sections that are towards the end of the page, since the user would never scroll far down enough to trigger those animations and reveal the hidden text.

**Comment by marcoow** [comment]
Hm, there seems to be a problem with the alternative solution:

https://user-images.githubusercontent.com/1510/186208920-beef11d1-9a5a-4eca-9c8c-ca21f729eea6.mov

Also, can we make the animation a bit slower in general? I think with normal scrolling speeds, it would be so fast it seems like the entire bar just pops in.

**Comment by marianneciara** [comment]
That's odd, that looks like a bug that I thought I'd fixed Monday and I can't replicate it myself now. I've tweaked the animations and also tried to improve the speed as best I could (see below for more context on that). Can you check that's working OK for you now?

Regarding the speed of animation, it's challenging because given the height of these sections at different screen sizes, we have a small window of around 300px to start and finish the animation and have it look good at all sizes, i.e. completely cover the text when the section first enters into view and completely reveal it by the time we leave the section or reach the bottom of the page.

The hero at the top of the page is even more challenging because if we want the text completely covered when users at the top of the page, and revealed at least some time before they scroll past it (to allow it to be read), the window is between 200px and 50px at its smallest. 

From a UX perspective, users landing on these top hero sections won't yet know the "reveal-on-scroll" pattern and may try to interact with the text overlay to reveal the text (click, hover or even wait to see if it animates by itself). It may not be until they effectively give up and scroll past it that they realise how it works. My recommendation for these top sections would therefore be to either remove the overlay or have a time-based (vs. scroll-based) animation when the section is in view (although then the animation style wouldn't be consistent with other hero sections, unless we replace all animations with time-based ones).

Let me know your thoughts. Thanks!

**Comment by marcoow** [comment]
Hm, it seems broken in a different way now (Safari)?


https://user-images.githubusercontent.com/1510/187380920-411eaca5-212e-40fa-aae8-a29155ae648b.mov

If we can't get it to work, we'll have to remove it for launch but we'd really like to have it…

**Comment by marianneciara** [comment]
@marcoow I've set some time aside on Friday to take a look at this and issue #1845. I'll update you then.

**Comment by marianneciara** [comment]
@marcoow Were you looking at the latest preview link, https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app? The video shows the first preview URL I shared with you before we started using Netlify's review UI. Let me know if you're still seeing issues.

**Comment by marcoow** [comment]
oh, ok – looks like that was it :)
