### ISSUE TITLE
Remove focus outlines?

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1845]
Some elements have focus outlines when interacting with the page with the mouse which I think looks strange. Should those be removed or would that be bad for accessibility?
<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 25 09" src="https://user-images.githubusercontent.com/1510/185214952-4ce980eb-0371-4ec7-a166-52bbd39ef7d5.png">

(see the "X" and "Services" here)

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 25 07" src="https://user-images.githubusercontent.com/1510/185214937-00d40b71-c9f5-42de-8e2f-087b407fadfc.png">
<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 25 09" src="https://user-images.githubusercontent.com/1510/185215004-e0da3ee7-906f-4939-a7ed-ba8b95907e41.png">

**Comment by marianneciara** [comment]
This only happens when you open/close the submenu right? Since it's a full page modal we need to move the focus inside the modal and trap it there until the user closes it, and once it's closed, we return focus to the button that toggled the menu. 

Looking at the [docs for the focus method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) there is an option to force visible indication (or not), but it's not well supported and the "_browser may still provide visible indication if it determines that this would improve accessibility for users._"

To mitigate the issue I've moved the focus to the container itself instead of the close icon (this seems to be a common approach anyway) and added the `focusVisible: false` option wherever focus is managed programmatically, for those browsers that do/will support it. Let me know if that works for you.

**Comment by marcoow** [comment]
Hm, I think it happens when I close the submenu/modal with ESC:

<img width="442" alt="Bildschirmfoto 2022-08-23 um 18 10 26" src="https://user-images.githubusercontent.com/1510/186208242-e4566320-938a-411b-b2f6-1f4613c9ebf0.png">

**Comment by marianneciara** [comment]
Ah yes that makes sense – since you're using your keyboard to close the modal, the browser may be inferring that you need that additional visual indication for improved accessibility. Let me know if you need anything else here or if we're good to close 👍

**Comment by marcoow** [comment]
Yes so I was thinking we want to remove the outlines?

**Comment by marianneciara** [comment]
So for accessibility reasons we do need keep the visible focus if a user is navigating the site with their keyboard (e.g. closing the modal with ESC, or tabbing through the elements). You'll notice that when you're not using your keyboard, the outline usually isn't visible even though those elements are technically in focus. This is because according to [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible), it's the user agent that decides via heuristics if the focus should be visible. Let me know if that makes sense or if you have any other questions.

**Comment by marcoow** [comment]
ok, makes sense – let's keep it then 👍
