### ISSUE TITLE
Improve Workshop pages

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2197]
We need to improve the workshop pages a bit.

Regular workshop pages (under https://mainmatter.com/services/workshops/):

* should we move the mentors below the workshop content (as the content seems more relevant)?

Specific landing pages (e.g. https://rust-telemetry-workshop.mainmatter.com):

* should we move the mentors below the workshop content (as the content seems more relevant)?
* make the call-to-action more prominent (we improved it for the telemetry workshop by adding the button in a few more places but that's kind of a quick fix – would be good to improve that further)
* we need to add pricing information somewhere

**Comment by yaigrie** [comment]
https://www.sketch.com/s/7baa7317-7ec9-48b5-9584-4edb6163c143/v/VqZLVl/p/23AE4AC6-CE60-4563-BCB4-E2B255A83B05/canvas#Version

If we separate the mentor from the hero image I would suggest to align it to the rest of the content and make a normal text section out of it. 
The pricing could also be a new text section, but we could also display it in the header or next to the booking buttons

For the CTA maybe instead of the fixed navbar, we could do a fixed single button in the bottom right of the page (like a horizontal fab element?)
