### ISSUE TITLE
Improve design of events list

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2383]
The events don't look great at the moment, in particular not the logos – one the [events page](http://mainmatter.com/events/):

![Bildschirmfoto 2024-04-30 um 17 41 46](https://github.com/mainmatter/mainmatter.com/assets/1510/4192fe33-08fd-4ad1-8210-c2493198a8d4)

as well as on the main [landing page](https://mainmatter.com): 

![Bildschirmfoto 2024-06-19 um 14 53 39](https://github.com/mainmatter/mainmatter.com/assets/1510/adbc94f0-9b53-4b28-aad1-27e977d8f1c8)

I think we should reconsider the layout and come up with sth. better.

**Comment by nchan0154** [comment]
I think part of the issue is bad curation, it looks a little better with a  nicer SVG logo:
![ws1](https://github.com/mainmatter/mainmatter.com/assets/12852862/dd63b719-1104-433f-ac2b-737c547c6206)

But also, we can consider aligning the logo to the top right to follow the existing components more (mobile, desktop)
![ws2](https://github.com/mainmatter/mainmatter.com/assets/12852862/0748bef6-4059-4801-9bed-9df79e75b491)
![ws3](https://github.com/mainmatter/mainmatter.com/assets/12852862/28521390-b928-41c1-aba6-6150b2111bc2)

We can also consider supporting a background color property in case the logo has a background that is not possible to remove.
![ws4](https://github.com/mainmatter/mainmatter.com/assets/12852862/7c0a3706-3a3d-493e-8424-fee9cfbec506)

Let me know what you think @marcoow

**Comment by marcoow** [comment]
I was thinking we could also use a background image maybe in addition to the logo like we do for the case studies for example:

![Bildschirmfoto 2024-06-21 um 14 56 56](https://github.com/mainmatter/mainmatter.com/assets/1510/c139cb99-3d75-4c7b-b1ad-3ebad05b581a)

That way I think we would make things a bit more exciting overall

**Comment by nchan0154** [comment]
Something like this?
![image](https://github.com/mainmatter/mainmatter.com/assets/12852862/66f50aaa-8710-42b7-8af2-e2af4d63fef8)

Currently, I've got the homepage cards looking like this, would you like backgrounds on the homepage event cards as well?
![image](https://github.com/mainmatter/mainmatter.com/assets/12852862/34b6e2b7-c7ad-4db6-a73f-d63baf1de84e)

**Comment by marcoow** [comment]
Yes, I was thinking something like this and for the cards on the homepage as well
