### ISSUE TITLE
Consider having external links open in new window

### ISSUE THREAD

**Issue by mansona** [mainmatter/mainmatter.com#487]
I'm not sure if this is a general rule but for things like liking to the twitter feel odd when they open in the same tab. 

This could 100% be a preference so please ignore and close if this doesn't make sense. 

If you want me to go through and try to audit which links I think should open in a new tab please let me know 👍

**Comment by pichfl** [comment]
`target="_blank"` was deprecated back in XHTML, but it's totally acceptable in HTML5 and I think it's only fair to mark external links that way. 

Since we're parsing the whole content at various points, we should consider automating that process, adding it to any link that isn't local to the page. 

Maybe @marcoow can integrate something into the build process here, which should be more efficient than manually looking 🙂

**Comment by mansona** [comment]
Not that I'm doing any of the actual work 😂 but I would recommend not adding an automated process for something like this because it's only a "nice to have" 👍 i.e. we add it to things that are obvious and improve it over time

**Comment by ghislaineguerin** [comment]
agree. external links should be opened in a new tab.

**Comment by pichfl** [comment]
Since we're already parsing the links anyway to add the necessary CSSBlocks classes and it's merely checking if the link is relative, it shouldn't be too hard to do and ensures that we don't miss anything.

And nice to have is highly relative, I think forcing this behavior is a good choice for us.

**Comment by marcoow** [comment]
For the blog posts, we have do it automatically but for all other links on the site we'll have to add it manually in the source.

**Comment by marcoow** [comment]
done via #514
